services:
  - type: web
    name: medical-report-charter
    runtime: docker
    plan: free
    envVars:
      - key: DROPBOX_APP_KEY
        sync: false
      - key: DROPBOX_APP_SECRET
        sync: false
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: DROPBOX_FOLDER
        value: /
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: m-mittal/medical-charter
